price=float(input("enter you price "))
people=int(input("enter how many people "))
percent_tip=int(input("Enter percent for tip "))
to_pay=round (price*(1+percent_tip/100)/people, 2)
print (f"each person should be pay {to_pay} d")
